Some refactoring
Twitter-Public-Analysis/Twitter-Public-Analysis pull request #22
Opened 2020-09-12 08:27 UTC by keelimeguy

You may want to consider making some or all of these changes. Notice that the code moved out of the __init__.py files has been modified as well, sorry that the diffs don't capture that so easily..

(btw, I can't run the program on my machine at the moment, so can't verify the code functionality myself)

Regards!
Keelin

2020-09-12 08:29 UTC, keelimeguy commented on Dozent/DownloaderTools.py
> -    def download_pysmartdl(cls, link: str, verbose=True):
moved this further below, to be with other class methods

2020-09-12 08:29 UTC, keelimeguy commented on Dozent/DownloaderTools.py
> +    def download_pysmartdl(cls, link: str, verbose: bool = True):
only change is added type hints

2020-09-12 08:30 UTC, keelimeguy commented on Dozent/DownloaderTools.py
> -            f"axel --verbose --alternate --num-connections={DownloaderTools._connections_count} {link}")
no use in a classmethod with using the cls.. otherwise it would just be a staticmethod

2020-09-12 08:31 UTC, keelimeguy commented on Dozent/DownloaderTools.py
> -_downloaders = {
moved inside of class, where it makes more organizational sense

2020-09-12 08:31 UTC, keelimeguy commented on Dozent/__init__.py
> -import datetime
moved this code to its own file

2020-09-12 08:32 UTC, keelimeguy commented on Dozent/dozent.py
> +        for sample in data[start_index:end_index]:
renamed loop variable from `dict`, since that was a reserved name

2020-09-12 08:34 UTC, keelimeguy commented on Dozent/dozent.py
> +    _start_time = time.time()
adding underscore to all these `__name__ == "__main__"` variables, to highlight that they are global variables!

2020-09-12 08:34 UTC, keelimeguy commented on README.md
> +`python sentiment_analysis_app.py --topic-counts=3 --tweets-count=100 --clean-tweets`
seems cleaner to me like this

2020-09-12 08:36 UTC, keelimeguy commented on sentiment_analysis_app.py
> -    tweets_count_per_topic = [len(tweets_dict[list(tweets_dict.keys())[x]]) for x in
frankly not the best way to have implemented this. I'm also not confident that calling dict.keys() will always give the same ordering, so it may have been buggy

2020-09-12 08:38 UTC, keelimeguy commented on sentiment_analysis_app.py
> +    topics_list = list(tweets_dict.keys())[:topics_count]
slicing the list makes more sense than iterating over a range of the desired count...

2020-09-12 08:39 UTC, keelimeguy commented on sentiment_analysis_app.py
> +        total_tweets_count += len(tweets_dict[topic])
counting the sum in a single for loop is slightly faster than constructing a list just to loop over it again while summing

2020-09-12 08:40 UTC, keelimeguy commented on sentiment_analysis_app.py
> +    for topic, tweets in tweets_dict.items():
pretty sure that `dict.items()` returns a list of key,value tuples. Again, I couldn't run and test the code

2020-09-12 08:41 UTC, keelimeguy commented on sentiment_analysis_tools/__init__.py
> -from typing import Dict
moved to own file

2020-09-12 08:41 UTC, keelimeguy commented on sentiment_analysis_tools/sentiments.py
> +    __instance__ = None
decided to make this a singleton, since there was initializing code involved..

2020-09-12 08:42 UTC, keelimeguy commented on sentiment_analysis_tools/sentiments.py
> +            nltk.download('vader_lexicon', quiet=True)
this initializing code will be called at maximum once

2020-09-12 08:43 UTC, keelimeguy commented on sentiment_analysis_tools/sentiments.py
> +        return Sentiments.get_instance().NLTK_SENTIMENT_INTENSITY_ANALYZER.polarity_scores(text=text)['compound']
the previously global variables now come from the class singleton instance (which is initialized the first time it is called)

2020-09-12 08:44 UTC, keelimeguy commented on sentiment_analysis_tools/sentiments.py
> +    _sentiment_function_mapping = {
moved this inside the class for organizational reasons, and gave it a slightly more readable name.

2020-09-12 08:44 UTC, keelimeguy commented on sentiment_analysis_tools/sentiments.py
> +                cls._sentiment_function_mapping.items()}
again, using `dict.items()` to get the key,value pairs directly

2020-09-12 08:54 UTC, keelimeguy commented on sentiment_analysis_tools/sentiments.py
> +    @staticmethod
these were previously classmethods, but didn't make any use of the `cls` argument, so they are better off as static

2020-09-12 08:55 UTC, keelimeguy commented on sentiment_analysis_tools/sentiments.py
> +    pprint(Sentiments.multiple_sentiment_analysis(_sentence))
making use of the combined function, pretty-printing the returned dictionary

2020-09-12 16:20 UTC, v2thegreat requested changes

2020-09-12 16:20 UTC, v2thegreat commented on sentiment_analysis_app.py
> +    topics_list = list(tweets_dict.keys())[:topics_count]
This won't be an issue soon as we're going to have to re-write a ton of things for how we approach this and integrated Dash.
Going to have to review this manually later on

2020-09-12 16:20 UTC, v2thegreat commented on sentiment_analysis_app.py
> -    tweets_count_per_topic = [len(tweets_dict[list(tweets_dict.keys())[x]]) for x in
`dict.keys` preserves ordering for a while now: https://stackoverflow.com/a/39537308

2020-09-12 16:20 UTC, v2thegreat commented on sentiment_analysis_app.py
> +    for topic, tweets in tweets_dict.items():
Please run and test the code before making such commits

2020-09-12 16:20 UTC, v2thegreat commented on sentiment_analysis_tools/sentiments.py
> +            nltk.download('vader_lexicon', quiet=True)
Good idea, I wanted to figure out a way to do this myself. Are we sure that the RuntimeError is completely necessary?

2020-09-12 16:20 UTC, v2thegreat commented on sentiment_analysis_tools/sentiments.py
> +        return TextBlob(text=text).sentiment.polarity
Did you miss this one for the changes you made [here](https://github.com/Twitter-Public-Analysis/Twitter-Public-Analysis/pull/22/files#r487386574)?

2020-09-12 16:20 UTC, v2thegreat commented on sentiment_analysis_tools/sentiments.py
> +    _sentiment_function_mapping = {
Again, are you sure this works? I tried the same and ran into issues. I'll add it to my manual testing

2020-09-12 16:20 UTC, v2thegreat commented on sentiment_analysis_tools/sentiments.py
> +    pprint(Sentiments.multiple_sentiment_analysis(_sentence))
👍 for pprint

2020-09-12 17:21 UTC, keelimeguy commented on Dozent/DownloaderTools.py
> -    def download_pysmartdl(cls, link: str, verbose=True):
only personal organization, puts all the `download_*` functions nearer each other

2020-09-12 17:27 UTC, keelimeguy commented on sentiment_analysis_tools/sentiments.py
> +            nltk.download('vader_lexicon', quiet=True)
not necessary, but forces use of the get_instance() method rather than creating a Sentiments() object directly. Which makes it clearer that it is a singleton

2020-09-12 17:29 UTC, keelimeguy commented on sentiment_analysis_tools/sentiments.py
> +        return TextBlob(text=text).sentiment.polarity
I'm unable to follow that link to any particular place. What are you referring to?

2020-09-12 19:42 UTC, keelimeguy commented on Dozent/DownloaderTools.py
> -_downloaders = {
I have validated. Your errors in past may have come from not following this:
- the `DownloaderTools.` prefix needs removed as it is now within the class
- this dictionary needs to be defined after the functions, or else the definitions of the functions won't be found
- the `.__func__` suffix is needed as the functions are behind @classmethod decorators

2020-09-12 19:43 UTC, keelimeguy commented on Dozent/dozent.py
> +    _start_time = time.time()
done

2020-09-12 19:46 UTC, keelimeguy commented on sentiment_analysis_tools/sentiments.py
> +    _sentiment_function_mapping = {
positive that it works. I have made test code to cover this as well, which I can push to this PR if we'd like?

2020-09-12 19:55 UTC, keelimeguy commented on Dozent/__init__.py
> +__all__ = ['Dozent', ]
recommended by [PEP 8](https://www.python.org/dev/peps/pep-0008/#public-and-internal-interfaces)

> To better support introspection, modules should explicitly declare the names in their public API using the `__all__` attribute. Setting `__all__` to an empty list indicates that the module has no public API.

2020-09-12 19:56 UTC, keelimeguy commented on Dozent/DownloaderTools.py
> +        return f"\r {downloader_obj.url} [{status}] {num1} Mb / {num2} Mb @ {speed} {progress_bar} " \
`link` argument is unneeded since you can grab the url from the downloader object itself

2020-09-15 00:34 UTC, v2thegreat approved these changes

2020-09-15 00:34 UTC, v2thegreat commented on Dozent/DownloaderTools.py
> -_downloaders = {
have you validated functionality?

2020-09-15 00:34 UTC, v2thegreat commented on sentiment_analysis_tools/sentiments.py
> +            nltk.download('vader_lexicon', quiet=True)
👍

2020-09-15 00:53 UTC, merged