Creating unit tests
Twitter-Public-Analysis/Twitter-Public-Analysis pull request #23
Opened 2020-09-15 00:37 UTC by keelimeguy

2020-09-15 00:54 UTC, v2thegreat requested changes

2020-09-15 00:54 UTC, v2thegreat commented on sentiment_analysis_tools/sentiments.py
> +            return 0
Use NaN instead of 0 for this

2020-09-15 00:54 UTC, v2thegreat commented on sentiment_analysis_tools/sentiments.py
> +            return 0
Use NaN instead of 0 for this

2020-09-15 00:54 UTC, v2thegreat commented on Dozent/tests/test_downloader_tools.py
> +import unittest
Move `tests` to it's own directory

2020-09-23 04:03 UTC, v2thegreat commented on .github/workflows/python-app.yml
> +on: [push, pull_request, workflow_dispatch]
Any major reason for switching this? Wouldn't it be better to only run this only for the master branch and run the tests manually? Just want your thoughts

2020-09-23 04:04 UTC, v2thegreat commented on sentiment_analysis_tools/sentiments.py
> +            return math.nan
Good add

2020-09-23 04:05 UTC, v2thegreat commented on tests/test_sentiments.py
> +        self.assertEqual(expected_output, Sentiments.multiple_sentiment_analysis(''))
Good test. We might want to add something for future tests to check if common sentences are positive or negative

2020-09-23 04:05 UTC, v2thegreat approved these changes

2020-09-23 04:06 UTC, merged

2020-09-23 22:43 UTC, keelimeguy commented on .github/workflows/python-app.yml
> +on: [push, pull_request, workflow_dispatch]
I don't have access to the API for this branch (missing permissions) and the button does not show up in the GUI except for on actions of the master branch. Therefore, since these PRs have been going to Dozent, there has been no way for me to manually trigger a test.

2020-09-23 22:46 UTC, keelimeguy commented on .github/workflows/python-app.yml
> +on: [push, pull_request, workflow_dispatch]
Not to mention, I have never seen the GUI button show up for the manual workflow_dispatch hook, so I have doubts if it even works. I've only been able to trigger manual tests in my own repos using the API

2020-09-23 23:14 UTC, keelimeguy commented on .github/workflows/python-app.yml
> +on: [push, pull_request, workflow_dispatch]
I'll correct myself, I can see the button on my forked repo, but not here. Likely a permissions issue still.

![image](https://user-images.githubusercontent.com/10254213/94083349-e7ab2780-fdd0-11ea-8cf1-ed58f161a557.png)